### ISSUE TITLE
Add ability to store/rename debug log in different path

### ISSUE THREAD

**Issue by jwwicks** [ptv-logistics/Log4ALA#1]
As an Log Analytics appender user I would like for the debug logfile configuration settings to allow for the renaming and placement of the debug log so that restricted paths such as the Program Files directory do not cause lock errors. 

log4net:ERROR [RollingFileAppender] ErrorCode: GenericFailure. Unable to acquire lock on file C:\Program Files (x86)\LINQPad5\log4ALA_info.log.

**Comment by moberacker** [comment]
change request done => new version available as Nuget package Log4ALA 1.0.4
