### ISSUE TITLE
Application Output Window is too chatty

### ISSUE THREAD

**Issue by bknabel** [ptv-logistics/Log4ALA#12]
When using Log4ALA I'm finding that our Output window is polluted with the following messages pretty frequently:
   Getting "enableDebugConsoleLog" from ServiceRuntime: FAIL.
   Getting "enableDebugConsoleLog" from ConfigurationManager: FAIL.

This appears to be because CloudConfigurationManager.GetSetting is overly chatty. I've reproduced this using the Log4ALA test code.

Would it be possible to store the value retrieved by the CloudConfigurationManager during the first call and use that value instead of relying on CloundConfigurationManager.GetSetting every time that get ALAEnableDebugConsoleLog is called?

That might improve performance in a miniscule way but it would make our our trace output much more readable.

**Comment by moberacker** [comment]
The new version (NuGet package) will be available maybe in the course of this week...

**Comment by bknabel** [comment]
Awesome. I need to buy you a pizza or something...

**Comment by moberacker** [comment]
Hi Brad, where's my pizza...the new NuGet package 2.4.0 is available...:wink:
