### ISSUE TITLE
Update nuget dependencies to use Microsoft.Azure.ConfigurationManager

### ISSUE THREAD

**Issue by philchuang** [ptv-logistics/Log4ALA#13]
The nuget package Microsoft.WindowsAzure.ConfigurationManager has been deprecated in favor of Microsoft.Azure.ConfigurationManager

**Comment by moberacker** [comment]
ok thanks I'll update the dependency asap...with the next release.

**Comment by philchuang** [comment]
I made the change [here](https://github.com/philchuang/Log4ALA/commit/d3da96320cab89d09ca02cf839b4d40c22bf198c), but I didn't get a chance to run the tests.

I had to update from .NET 4.5 to .NET 4.5.2 in order to add the new package.

**Comment by moberacker** [comment]
Fixed with version Log4ALA 2.5.0
