### ISSUE TITLE
Azure Gov ALA workspaces not supported

### ISSUE THREAD

**Issue by philchuang** [ptv-logistics/Log4ALA#14]
Azure commercial workspaces use the format {workSpaceID}.ods.opinsights.azure.com.

But Azure government workspaces use the format {workSpaceID}.ods.opinsights.azure.**us**.

The URL suffix is hard-coded in AlaTcpClient, and needs to be configurable in order to support non-commercial workspaces.

**Comment by moberacker** [comment]
Fixed with version Log4ALA 2.5.0

**Comment by philchuang** [comment]
Thanks! I'm trying it out now
