### ISSUE TITLE
Method SerializeLoggingEvent is causing deadlocks because of IDictionary

### ISSUE THREAD

**Issue by colutti** [ptv-logistics/Log4ALA#17]
We are using Log4ALA to send 10,000,000 logs to log analytics every day. We have seen a lot of threads getting deadlock and we took a process dump to analyze what might be causing the issue. 

We have identified that this method `SerializeLoggingEvent` is causing deadlocks because it should use a `ConcurrentDictionary` instead of an `IDictionary`. The variable created inside this method is being passed to other methods so the type of the variable should be changed in all classes. 

I am adding a screenshot of a dump that shows the problem. I am omitting data from it because of my company policy to not show sensitive information. 

![deadlock](https://user-images.githubusercontent.com/9368892/94714519-88a75e80-034c-11eb-85c8-211238ba988d.png)

**Comment by moberacker** [comment]
Hello Rafael,

can you please attach a screenshot of the exception...I can't see any in your screenshot there is only a .NET Call Stack...by the way in this case the [IDictionary interface will be implemented by the ExpandoObject ](https://github.com/ptv-logistics/Log4ALA/blob/e7d544a4f47a0f7f2977a095fb0a824c66746430/Log4ALA/LoggingEventSerializer.cs#L53 )which in my opinion is threadsafe please have a more detailed look at the implementation of [ExpandoObject IDictionary.Add implementation](https://github.com/microsoft/referencesource/blob/f461f1986ca4027720656a0c77bede9963e20b7e/System.Core/Microsoft/Scripting/Actions/ExpandoObject.cs#L567) which calls [TryAddMember](https://github.com/microsoft/referencesource/blob/f461f1986ca4027720656a0c77bede9963e20b7e/System.Core/Microsoft/Scripting/Actions/ExpandoObject.cs#L276) which in turn calls [TrySetValue](https://github.com/microsoft/referencesource/blob/f461f1986ca4027720656a0c77bede9963e20b7e/System.Core/Microsoft/Scripting/Actions/ExpandoObject.cs#L114) and this method uses a threadsafe lock...
