### ISSUE TITLE
Unloading AppDomain with ALA appender crashes application

### ISSUE THREAD

**Issue by sikemullivan** [ptv-logistics/Log4ALA#2]
I have a jobs system that runs the jobs independently in the own application domain. After completing, I drop the application domain. Since adding this appender, the application crashes on AppDomain.Unload . I can't toggle the use of this appender, and see that it is directly related. I created this issue with intent to contribute to this fix myself. Probably, something we can do to make sure that LogManager.Shutdown() works properly. I suspect that the Queues thread needs to be explicitly shutdown.

**Comment by moberacker** [comment]
Fixed with version Log4ALA 2.0.5 ...validation and indexing on nuget.org of package Log4ALA/2.0.5 in progress ...may take up to an hour.

**Comment by sikemullivan** [comment]
Nice! Thanks

**Comment by sikemullivan** [comment]
Fix is validated, app domain is shutting down 🥇
