### ISSUE TITLE
Initial connection failure takes down the application

### ISSUE THREAD

**Issue by sikemullivan** [ptv-logistics/Log4ALA#3]
If you fail to connect to Azure in this appender, it takes down the entire application. I would imagine a consumer would want their application to run. The logs would not be a reason for their application to go completely down.

**Comment by moberacker** [comment]
Fixed with version Log4ALA 2.0.5 ...validation and indexing on nuget.org of package Log4ALA/2.0.5 in progress ...may take up to an hour.

**Comment by sikemullivan** [comment]
Nice! Thanks
