### ISSUE TITLE
Question: Is it possible to disable logging to log4ALA_info.log?

### ISSUE THREAD

**Issue by bastianjohn** [ptv-logistics/Log4ALA#5]
Hi,

at first thanks for the great library! It works good for me.
I have a question regarding the local debug log file. How can i disable it to log a debug file to a local file path? I've only have seen the settings to edit the file path but in my case i don't want such a file. In my opinion the log4ALA_error.log is enough.

Thanks and best regards,
Bastian

**Comment by moberacker** [comment]
Hi Bastian,

I have added a new property disableInfoLogFile to avoid the info log file on production systems with disableInfoLogFile=true version Log4ALA 2.3.0

Best regards,
Markus

**Comment by bastianjohn** [comment]
Hi Markus,

thank you very much! I've tested it and it is working, only the error file is created 👍 Great work!

Best regards,
Bastian
